# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Whelmo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  # Crashlytics
  pod 'Fabric', '~> 1.7.6'
  pod 'Crashlytics', '~> 3.10.1'

  # Pods for Whelmo
  pod 'AppCenter/Crashes', '~> 1.6.0'
  pod 'AppCenter/Analytics', '~> 1.6.0'
  pod 'AppCenterReactNativeShared', '~> 1.5.0'

  node_modules_path = '../node_modules'
  react_native_path = node_modules_path + '/react-native'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'cxxreact',
    'CxxBridge',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTLinkingIOS',
    'RCTVibration',
    'RCTSettings',
    'RCTPushNotification',
    'RCTImage',
    'RCTGeolocation',
    'RCTCameraRoll',
    'RCTBlob',
    'RCTAnimation',
    'RCTActionSheet',
    'ART',
    'tvOS'
  ]

  pod 'RNVectorIcons', :path => node_modules_path + '/react-native-vector-icons'
  pod 'RNI18n', :path => node_modules_path + '/react-native-i18n'
  pod 'RNSVG', :path => node_modules_path + '/react-native-svg'
  pod 'react-native-splash-screen', :path => node_modules_path + '/react-native-splash-screen'
  pod 'RNKeychain', :path => node_modules_path + '/react-native-keychain'
  pod 'RNShare', :path => node_modules_path + '/react-native-share'
  pod 'CodePush', :path => node_modules_path + '/react-native-code-push'
  pod 'react-native-google-analytics-bridge', :path => node_modules_path + '/react-native-google-analytics-bridge'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "RNSVG"
      target.build_configurations.each do |config|
        config.build_settings['GCC_NO_COMMON_BLOCKS'] = 'NO'
      end
    end

    # Fixes Archive issue
    # https://github.com/facebook/react-native/issues/12814#issuecomment-321947367
    if target.name == "React"
      target.remove_from_project
    end
  end
end